[workspace]
authors = ["david-dorf <davidjohndorf@gmail.com>"]
channels = ["conda-forge"]
description = "Robot model format using Python instead of XML for better type checking, logic, scripting, and parsing."
name = "marionette"
platforms = ["linux-64", "osx-arm64", "osx-64", "win-64"]
version = "0.1.0"

[tasks]
move_franka = "pixi run python3 src/examples/move_franka.py"
attach_franka = "pixi run python3 src/examples/attach_franka.py"
multiple_frankas = "pixi run python3 src/examples/multiple_frankas.py"
mujoco_franka = "pixi run python3 src/examples/mujoco_franka.py"

[target.osx.tasks]
mujoco_franka = "pixi run mjpython src/examples/mujoco_franka.py"

[dependencies]
python = ">=3.13,<3.14"
rust = ">=1.84.0,<1.85"
rerun-sdk = ">=0.22.1, <0.23.0"

[pypi-dependencies]
marionette = { path = "./src", editable = true }
