[workspace]
authors = ["david-dorf <davidjohndorf@gmail.com>"]
channels = ["conda-forge"]
description = "Robot model format using Python instead of XML for better type checking, logic, scripting, and parsing."
name = "marionette"
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.1,<3.14"
rust = ">=1.84.0,<1.85"
rerun-sdk = ">=0.22.1, <0.23.0"

[pypi-dependencies]
genesis-world = ">=0.2.1, <0.3.0"
marionette = { path = "./marionette", editable = true }
