[workspace]
authors = ["david-dorf <davidjohndorf@gmail.com>"]
channels = ["conda-forge"]
description = "Robot model format using Python instead of XML for better type checking, logic, scripting, and parsing."
name = "marionette"
platforms = ["linux-64", "osx-arm64", "osx-64", "win-64"]
version = "0.1.0"

[tasks]
move_franka = "pixi run python3 src/examples/move_franka.py"
attach_franka = "pixi run python3 src/examples/attach_franka.py"
multiple_frankas = "pixi run python3 src/examples/multiple_frankas.py"

[dependencies]
python = ">=3.10,<3.12"
rust = ">=1.84.0,<1.85"
numpy = "==1.26.4"
pillow = ">=9.2.0, <11.0.0"
rerun-sdk = ">=0.22.1, <0.23.0"

[pypi-dependencies]
marionette = { path = "./src", editable = true }
